# Generated by Django 2.2 on 2019-06-27 07:16

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('blog_index_title', models.CharField(max_length=255, null=True)),
                ('blog_index_subtitle', wagtail.core.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Blog Index Page',
                'verbose_name_plural': 'Blog Index Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('blog_title', models.CharField(max_length=255, null=True)),
                ('blog_subtitle', models.CharField(max_length=255, null=True)),
                ('blog_body', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('blog_content', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'blog Page',
                'verbose_name_plural': 'Blog  Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
