# Generated by Django 2.2 on 2019-06-27 07:23

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='blog_index_subtitle',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
