# Generated by Django 2.2 on 2019-06-27 08:43

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20190627_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='blog_content',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
