# Generated by Django 2.2 on 2019-06-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_auto_20190627_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='blog_date',
            field=models.DateField(blank=True, null=True, verbose_name='Blog Post date'),
        ),
    ]
