# Generated by Django 2.2 on 2019-06-27 13:38

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_auto_20190627_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='blog_content',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BlogPageContent',
        ),
    ]
