# Generated by Django 2.2 on 2019-06-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_auto_20190627_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='blog_creator',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
