# Generated by Django 2.2 on 2019-06-27 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0010_blogpage_blog_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='blog_creator',
            new_name='blog_creator_name',
        ),
    ]
