# Generated by Django 2.2 on 2019-06-28 05:58

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0011_auto_20190627_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogExtraDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('add_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('add_more_content', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_detail', to='myblog.BlogPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
