# Generated by Django 2.2 on 2019-06-28 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('myblog', '0012_blogextradetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('welcome_title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Welcome Page',
                'verbose_name_plural': 'Welcome Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
