# Generated by Django 2.2 on 2019-06-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('myblog', '0013_welcomepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WelcomePage',
        ),
    ]
